name: AWS 3.8.17
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.17
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.17
    - name: Install dependencies
      run: |
        make install-aws
